name: NPM publish

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    transpile-patch-publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install dependencies
              run: yarn add --dev typescript @types/react @types/react-dom

            - name: Transpile typescript to javascript and pack in dist folder
              run: scripts/transpile-and-move.sh

            - name: Point to "index.js" intead to "index.tsx"
              run: perl -pi -e "s/dist\/index.tsx/dist\/index.js/g" package.json

            - name: Remove dependencies
              run: yarn remove typescript @types/react @types/react-dom

            - id: publish
              uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
            - if: steps.publish.type != 'none'
              run: |
                  echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
